version: "3"
services: 
    app:
        build: .
        volumes: 
            - ".:/app"
        ports: 
            - "80:80"
        tty: true
    
    db:
        build: ./db
        ports:
            - "3306:3306"
        volumes:
            - ./data
        environment: 
            MYSQL_ROOT_PASSWORD: root

        tty: true