version: "3"
services: 
    app:
        restart: always
        build: .
        container_name: 'python3'
        working_dir: '/root/'
        tty: true
        volumes:
          - ./app/opt:/root/opt
    
    
    db:
        build: ./db
        ports:
            - "3306:3306"
        volumes:
            - ./data
        environment: 
            MYSQL_ROOT_PASSWORD: root

        tty: true